[package]
name = "r3_kernel"
version = "0.0.1"
authors = ["Narasimha1997 <yogaimpression@gmail.com>"]
edition = "2018"

[dependencies]
bootloader = {version = "0.10.9", path="../third_party/crates/bootloader"}

[package.metadata.bootimage]
build-command = ["xbuild"]
